name: quiz_ui_core
description: "Core UI presentation components and widgets for Quiz App"
version: 1.0.0
# publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

